@startuml Inventary Use Case Diagram

' Definición de estilos
skinparam usecase {
  BackgroundColor LightBlue
  BorderColor DarkSlateGray
  ArrowColor Navy
  ActorBorderColor DarkSlateGray
  ActorBackgroundColor Wheat
}

skinparam rectangle {
  BackgroundColor AliceBlue
  BorderColor DarkSlateGray
}

' Definición de actores
:Administrador: as admin #Pink
:Jefe de inventario: as inventary #LightGreen
:Despachador: as dispatcher #LightYellow
:Repartidor: as niceGuy #LightCyan

' Sistema principal
rectangle "Sistema de Master Bread" {
  
  ' Jefe de inventario
  together {
    (Registrar pedido) as UC1
    (Ver inventario) as UC2
    (Reclamar un pedido) as UC3
    (Agregar producto) as UC4
    (Editar cantidad de producto) as UC9
  }
  
  ' Administrador
  together {
    (Hacer reporte de envios diarios) as UC5
    (Hacer reporte de inventario) as UC6
    (Hacer reporte de despachos) as UC7
  }

  ' Repartidor
  together{
    (Marcar un pedido como exitoso) as UC10
    (Marcar pedido como fallido o erroneo) as UC12
  }
  
  ' Despachador
  together{
    (Crear factura) as UC11
    (Añade producto solicitado a envio) as UC13
    (Añade direccion de envio) as UC14
    (Añade nombre he id de pedido) as UC15
  }

  (Iniciar sesion) as UC18
  (Ver menu) as UC8
  (Cerrar sesion) as UC16
  (Olvide contraseña) as UC17
  (Registrarse) as UC19

}

' Relaciones de los actores
admin --> UC5
admin --> UC6
admin --> UC7
admin -- UC8
admin -- UC18

inventary --> UC2
inventary --> UC4
inventary -- UC8
inventary -- UC18
inventary --> UC9

dispatcher --> UC1
dispatcher -- UC8
dispatcher -- UC18
dispatcher --> UC11

niceGuy --> UC3
niceGuy -- UC8
niceGuy -- UC18
niceGuy --> UC10
niceGuy --> UC12

' Relaciones de inclusión
UC11 ..> UC13 : <<include>>
UC13 ..> UC14 : <<include>>
UC14 ..> UC15 : <<include>>
UC8 ..> UC16 : <<extend>>
UC18 ..> UC17 : <<extend>>
UC18 ..> UC19 : <<extend>>



' Notas explicativas
note right of UC11 : Proceso de\ncreación de factura

@enduml