@startuml Inventory Use Case Diagram
' Definición de estilos
skinparam usecase {
  BackgroundColor LightBlue
  BorderColor DarkSlateGray
  ArrowColor Navy
  ActorBorderColor DarkSlateGray
  ActorBackgroundColor Wheat
}
skinparam rectangle {
  BackgroundColor AliceBlue
  BorderColor DarkSlateGray
}
' Definición de actores
:Administrador: as admin #Pink
:Jefe de inventario: as inventory #LightGreen
:Despachador: as dispatcher #LightYellow
:Repartidor: as deliveryGuy #LightCyan

' Sistema principal
rectangle "Sistema de Master Bread" {
  ' Casos de uso comunes
  (Iniciar sesión) as UC1
  (Ver menú) as UC2
  (Cerrar sesión) as UC3
  
  ' Jefe de inventario
  (Ver inventario) as UC4
  (Agregar producto) as UC5
  (Editar cantidad de producto) as UC6
  
  ' Administrador
  (Generar reporte de envíos diarios) as UC7
  (Generar reporte de inventario) as UC8
  (Generar reporte de despachos) as UC9
  
  ' Despachador
  (Registrar pedido) as UC10
  (Crear factura) as UC11
  
  ' Repartidor
  (Reclamar pedido) as UC12
  (Marcar pedido como exitoso) as UC13
  (Marcar pedido como fallido o erróneo) as UC14
  
  ' Extensiones
  (Recuperar contraseña) as UC15
  (Registrarse) as UC16
}

' Relaciones de los actores
admin --> UC1
admin --> UC2
admin --> UC3
admin --> UC7
admin --> UC8
admin --> UC9

inventory --> UC1
inventory --> UC2
inventory --> UC3
inventory --> UC4
inventory --> UC5
inventory --> UC6

dispatcher --> UC1
dispatcher --> UC2
dispatcher --> UC3
dispatcher --> UC10
dispatcher --> UC11

deliveryGuy --> UC1
deliveryGuy --> UC2
deliveryGuy --> UC3
deliveryGuy --> UC12
deliveryGuy --> UC13
deliveryGuy --> UC14

' Relaciones de extensión
UC1 <.. UC15 : <<extend>>
UC1 <.. UC16 : <<extend>>

' Relaciones de inclusión
UC11 ..> (Añadir producto solicitado a envío) : <<include>>
UC11 ..> (Añadir dirección de envío) : <<include>>
UC11 ..> (Añadir nombre e ID de pedido) : <<include>>

' Notas explicativas
note right of UC11 : Proceso de\ncreación de factura

@enduml